openapi: 3.0.1

info:
  title: API Tipo de Pessoas
  version: 1.0.1
  description: "Documentação para acesso a API Tipo de Pessoas"

servers:
- url: http://localhost:5000/

tags:
- name: Pessoas

paths:
  # Pessoas
  /pessoas:
    #LISTAR REGISTROS
    get:
      tags:
      - Pessoas
      summary: Lista todos os dados da API Pessoas
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/response'
        404:
          description: Nenhuma registro encontrado
          content: {}
        500:
          description: Internal Server Error
          content: {}
    
    #CADASTRAR REGISTROS
    post:
      security:
        - bearerAuth: []
      tags:
      - Pessoas
      summary: Adiciona um novo registro na API Pessoas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post'
        required: true
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        500:
          description: Internal Server Error
          content: {}
    
    #ATAULIZAR REGISTROS
    patch:
      security:
        - bearerAuth: []
      tags:
      - Pessoas
      summary: Altera dados de uma categoria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patch'
        required: true
      responses:
        202:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        404:
          description: Nenhuma categoria cadastrada com esse id
          content: {}
        500:
          description: Internal Server Error
          content: {}
    
    #APAGAR REGISTROS
    delete:
      security:
        - bearerAuth: []
      tags:
      - Pessoas
      summary: Deleta uma categoria através do seu id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        404:
          description: Nenhuma categoria cadastrada com esse id
          content: {}
        500:
          description: Internal Server Error
          content: {}

  /pessoas/{id}:
    #LISTAR REGISTRO ESPECÍFICO
    get:
      tags:
      - Pessoas
      summary: Lista uma categoria através do seu id
      parameters:
      - name: id
        in: path
        description: id da categoria
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
        404:
          description: Nenhuma categoria cadastrada com esse id
          content: {}
        500:
          description: Internal Server Error
          content: {}

  # Login
  /users/login:
    #Autenticação de Usuários
    post:
      tags:
      - Login
      summary: Realiza a autenticação de usuários e gera token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/login'
        401:
          description: Usuário não autenticado
          content: {}
        404:
          description: Nenhuma registro encontrado
          content: {}
        500:
          description: Internal Server Error
          content: {}
  
#SCHEMA
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    response:
      required:
      - TPP_PRIM
      - TPP_NOME
      - TPP_SIGL
      - TPP_STAT
      type: object
      properties:
        TTP_PRIM:
          type: integer
          example: 1
        TTP_NOME:
          type: string
          example: "Pessoa Física"
        TTP_SIGL:
          type: string
          example: "PF"
        TTP_STAT:
          type: integer
          example: 1
    post:
      required:
      - nome
      - sigla
      - status
      type: object
      properties:
        nome:
          type: string
          example: "Pessoa Física"
        sigla:
          type: string
          example: "PF"
        status:
          type: integer
          example: 1
    patch:
      required:
      - id
      - nome
      - sigla
      - status
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: "Pessoa Física"
        sigla:
          type: string
          example: "PF"
        status:
          type: integer
          example: 1
    delete:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          example: 1
    user:
      required:
      - usuario
      - senha
      type: object
      properties:
        usuario:
          type: string
          example: "user"
        senha:
          type: string
          example: "password"
    login:
      type: object
      properties:
        code:
          type: integer
          example: 200
        msg:
          type: string
          example: "Usuário autenticado com sucesso!"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImFsZW5hc...."
security:
  - bearerAuth: []